export const SOCKET_CONNECTED = 'SOCKET_CONNECTED'
export const SOCKET_DISCONNECTED = 'SOCKET_DISCONNECTED'
export const SOCKET_RECONNECTING = 'SOCKET_RECONNECTING'

export const SOCKET_LOAD_DATA = 'SOCKET_LOAD_DATA'
export const SOCKET_LOADED_DATA = 'SOCKET_LOADED_DATA'

export const SOCKET_SELECT_DATA = 'SOCKET_SELECT_DATA'
export const SOCKET_SELECTED_DATA = 'SOCKET_SELECTED_DATA'

export const SOCKET_CREATE_DATA = 'SOCKET_CREATE_DATA'
export const SOCKET_CREATED_DATA = 'SOCKET_CREATED_DATA'

export const SOCKET_UPDATE_DATA = 'SOCKET_UPDATE_DATA'
export const SOCKET_UPDATED_DATA = 'SOCKET_UPDATED_DATA'
